'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.34003
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

Namespace Cotizacion
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Moneda", [Namespace]:="http://tempuri.org/")>  _
    Public Enum Moneda As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Peso = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Dolar = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Real = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Cotizacion.CotizacionSoap")>  _
    Public Interface CotizacionSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Obtener", ReplyAction:="*")>  _
        Function Obtener(ByVal moneda As Cotizacion.Moneda) As Single
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface CotizacionSoapChannel
        Inherits Cotizacion.CotizacionSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CotizacionSoapClient
        Inherits System.ServiceModel.ClientBase(Of Cotizacion.CotizacionSoap)
        Implements Cotizacion.CotizacionSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Obtener(ByVal moneda As Cotizacion.Moneda) As Single Implements Cotizacion.CotizacionSoap.Obtener
            Return MyBase.Channel.Obtener(moneda)
        End Function
    End Class
End Namespace
